/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum29062026;

/**
 *
 * @author zakiv
 */
public class FormMinuman extends javax.swing.JFrame {

    /**
     * Creates new form FormMinuman
     */
    
    private FormUtama utama;

    public FormMinuman(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }
    
    public FormMinuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormMinuman = new javax.swing.JLabel();
        cbEsteh = new javax.swing.JCheckBox();
        cbExtrajos = new javax.swing.JCheckBox();
        cbNutrisari = new javax.swing.JCheckBox();
        txtEsteh = new javax.swing.JTextField();
        txtExtrajos = new javax.swing.JTextField();
        txtNutrisari = new javax.swing.JTextField();
        ckbEsteh = new javax.swing.JComboBox<>();
        ckbExtrajos = new javax.swing.JComboBox<>();
        ckbNutrisari = new javax.swing.JComboBox<>();
        txtTotalEsteh = new javax.swing.JTextField();
        txtTotalExtrajos = new javax.swing.JTextField();
        txtTotalNutrisari = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotalMinuman = new javax.swing.JButton();
        txtTotalMinuman = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormMinuman.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFormMinuman.setText("Pilihan Menu Minuman");

        cbEsteh.setText("Esteh");
        cbEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstehActionPerformed(evt);
            }
        });

        cbExtrajos.setText("Extrajos");
        cbExtrajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbExtrajosActionPerformed(evt);
            }
        });

        cbNutrisari.setText("Nutrisari");
        cbNutrisari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNutrisariActionPerformed(evt);
            }
        });

        txtEsteh.setEditable(false);

        txtExtrajos.setEditable(false);

        txtNutrisari.setEditable(false);

        ckbEsteh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ckbEsteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbEstehActionPerformed(evt);
            }
        });

        ckbExtrajos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ckbExtrajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbExtrajosActionPerformed(evt);
            }
        });

        ckbNutrisari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ckbNutrisari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNutrisariActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotalMinuman.setText("Total");
        btnTotalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalMinumanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblFormMinuman))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbNutrisari, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNutrisari))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbExtrajos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtExtrajos))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cbEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ckbExtrajos, javax.swing.GroupLayout.Alignment.LEADING, 0, 85, Short.MAX_VALUE)
                            .addComponent(ckbEsteh, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckbNutrisari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalEsteh)
                            .addComponent(txtTotalExtrajos)
                            .addComponent(txtTotalNutrisari, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnTotalMinuman)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormMinuman)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEsteh)
                    .addComponent(txtEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalEsteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExtrajos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbExtrajos)
                    .addComponent(ckbExtrajos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalExtrajos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNutrisari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNutrisari)
                    .addComponent(ckbNutrisari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalNutrisari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalMinuman)
                    .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnKembali)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalMinumanActionPerformed
        double a = Double.parseDouble(txtTotalEsteh.getText());
        double b = Double.parseDouble(txtTotalExtrajos.getText());
        double c = Double.parseDouble(txtTotalNutrisari.getText());
        double total = a + b + c;
        txtTotalMinuman.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalMinumanActionPerformed

    private void cbEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstehActionPerformed
        txtEsteh.setText("5000");
    }//GEN-LAST:event_cbEstehActionPerformed

    private void cbExtrajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExtrajosActionPerformed
        txtExtrajos.setText("6000");
    }//GEN-LAST:event_cbExtrajosActionPerformed

    private void cbNutrisariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNutrisariActionPerformed
        txtNutrisari.setText("6000");
    }//GEN-LAST:event_cbNutrisariActionPerformed

    private void ckbEstehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbEstehActionPerformed
        int jumlah = (int)ckbEsteh.getSelectedIndex();
        double harga = Double.parseDouble(txtEsteh.getText());
        double total = jumlah * harga;
        txtTotalEsteh.setText(Double.toString(total));
    }//GEN-LAST:event_ckbEstehActionPerformed

    private void ckbExtrajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbExtrajosActionPerformed
        int jumlah = (int)ckbExtrajos.getSelectedIndex();
        double harga = Double.parseDouble(txtExtrajos.getText());
        double total = jumlah * harga;
        txtTotalExtrajos.setText(Double.toString(total));
    }//GEN-LAST:event_ckbExtrajosActionPerformed

    private void ckbNutrisariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNutrisariActionPerformed
        int jumlah = (int)ckbNutrisari.getSelectedIndex();
        double harga = Double.parseDouble(txtNutrisari.getText());
        double total = jumlah * harga;
        txtTotalNutrisari.setText(Double.toString(total));
    }//GEN-LAST:event_ckbNutrisariActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMinuman.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalMinuman;
    private javax.swing.JCheckBox cbEsteh;
    private javax.swing.JCheckBox cbExtrajos;
    private javax.swing.JCheckBox cbNutrisari;
    private javax.swing.JComboBox<String> ckbEsteh;
    private javax.swing.JComboBox<String> ckbExtrajos;
    private javax.swing.JComboBox<String> ckbNutrisari;
    private javax.swing.JLabel lblFormMinuman;
    private javax.swing.JTextField txtEsteh;
    private javax.swing.JTextField txtExtrajos;
    private javax.swing.JTextField txtNutrisari;
    private javax.swing.JTextField txtTotalEsteh;
    private javax.swing.JTextField txtTotalExtrajos;
    private javax.swing.JTextField txtTotalMinuman;
    private javax.swing.JTextField txtTotalNutrisari;
    // End of variables declaration//GEN-END:variables
}
