/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum29062026;

/**
 *
 * @author HYPE AMD
 */
public class FormMakanan extends javax.swing.JFrame {

    /**
     * Creates new form FormMakanan
     */
    private FormUtama utama;

    public FormMakanan(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }
    
    
    public FormMakanan() {
        initComponents();
        txtMieAyam.setEditable(false);
        txtBakso.setEditable(false);
        txtMieAyamBakso.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbMieAyam = new javax.swing.JCheckBox();
        cbBakso = new javax.swing.JCheckBox();
        cbMieAyamBakso = new javax.swing.JCheckBox();
        txtMieAyam = new javax.swing.JTextField();
        txtBakso = new javax.swing.JTextField();
        txtMieAyamBakso = new javax.swing.JTextField();
        ckbMieAyam = new javax.swing.JComboBox<>();
        ckbBakso = new javax.swing.JComboBox<>();
        ckbMieAyamBakso = new javax.swing.JComboBox<>();
        txtTotalMieAyam = new javax.swing.JTextField();
        txtTotalBakso = new javax.swing.JTextField();
        txtTotalMieAyamBakso = new javax.swing.JTextField();
        txtTotalMakanan = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotalMakanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Pilihan Menu Makanan");

        cbMieAyam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMieAyam.setText("Mie Ayam");
        cbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieAyamActionPerformed(evt);
            }
        });

        cbBakso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbBakso.setText("Bakso");
        cbBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBaksoActionPerformed(evt);
            }
        });

        cbMieAyamBakso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMieAyamBakso.setText("Mie Ayam Bakso");
        cbMieAyamBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieAyamBaksoActionPerformed(evt);
            }
        });

        ckbMieAyam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ckbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMieAyamActionPerformed(evt);
            }
        });

        ckbBakso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ckbBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbBaksoActionPerformed(evt);
            }
        });

        ckbMieAyamBakso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ckbMieAyamBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMieAyamBaksoActionPerformed(evt);
            }
        });

        txtTotalBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBaksoActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotalMakanan.setText("Total");
        btnTotalMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalMakananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMieAyam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbBakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMieAyamBakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMieAyamBakso, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMieAyam, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(txtBakso)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ckbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ckbBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ckbMieAyamBakso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalMieAyamBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTotalMakanan)
                .addGap(18, 18, 18)
                .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMieAyam)
                    .addComponent(txtMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBakso)
                    .addComponent(ckbBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMieAyamBakso)
                    .addComponent(txtMieAyamBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbMieAyamBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMieAyamBakso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotalMakanan))
                .addGap(81, 81, 81)
                .addComponent(btnKembali)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBaksoActionPerformed

    private void cbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieAyamActionPerformed
        txtMieAyam.setText("15000");
    }//GEN-LAST:event_cbMieAyamActionPerformed

    private void cbBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBaksoActionPerformed
        txtBakso.setText("12000");
    }//GEN-LAST:event_cbBaksoActionPerformed

    private void cbMieAyamBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieAyamBaksoActionPerformed
        txtMieAyamBakso.setText("18000");
    }//GEN-LAST:event_cbMieAyamBaksoActionPerformed

    private void ckbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMieAyamActionPerformed
        int jumlah = (int)ckbMieAyam.getSelectedIndex();
        double harga = Double.parseDouble(txtMieAyam.getText());
        double total = jumlah * harga;
        txtTotalMieAyam.setText(Double.toString(total));
    }//GEN-LAST:event_ckbMieAyamActionPerformed

    private void ckbBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbBaksoActionPerformed
        int jumlah = (int)ckbBakso.getSelectedIndex();
        double harga = Double.parseDouble(txtBakso.getText());
        double total = jumlah * harga;
        txtTotalBakso.setText(Double.toString(total));
    }//GEN-LAST:event_ckbBaksoActionPerformed

    private void ckbMieAyamBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMieAyamBaksoActionPerformed
        int jumlah = (int)ckbMieAyamBakso.getSelectedIndex();
        double harga = Double.parseDouble(txtMieAyamBakso.getText());
        double total = jumlah* harga;
        txtTotalMieAyamBakso.setText(Double.toString(total));
    }//GEN-LAST:event_ckbMieAyamBaksoActionPerformed

    private void btnTotalMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalMakananActionPerformed
        double a = Double.parseDouble(txtTotalMieAyam.getText());
        double b = Double.parseDouble(txtTotalBakso.getText());
        double c = Double.parseDouble(txtTotalMieAyamBakso.getText());
        double total = a + b + c;
        txtTotalMakanan.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalMakananActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMakanan.getText();
        utama.setTotalMakan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalMakanan;
    private javax.swing.JCheckBox cbBakso;
    private javax.swing.JCheckBox cbMieAyam;
    private javax.swing.JCheckBox cbMieAyamBakso;
    private javax.swing.JComboBox<String> ckbBakso;
    private javax.swing.JComboBox<String> ckbMieAyam;
    private javax.swing.JComboBox<String> ckbMieAyamBakso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBakso;
    private javax.swing.JTextField txtMieAyam;
    private javax.swing.JTextField txtMieAyamBakso;
    private javax.swing.JTextField txtTotalBakso;
    private javax.swing.JTextField txtTotalMakanan;
    private javax.swing.JTextField txtTotalMieAyam;
    private javax.swing.JTextField txtTotalMieAyamBakso;
    // End of variables declaration//GEN-END:variables
}
